### ISSUE TITLE
Basic Auth fails with some Web Services

### ISSUE THREAD

**Issue by dansmith65** [proofgeist/generator#2]
Due to the default option in BaseElements plugin https://github.com/GoyaPtyLtd/BaseElements-Plugin/issues/78. Can get around it by encoding the user/pass in the URL, or by setting this curl option:

```
BE_Curl_Set_Option ( "CURLOPT_HTTPAUTH" ; 1 )
```

One webservice that this fails on is http://developer.helpscout.net/docs-api/

**Comment by toddgeist** [comment]
Nice
