### ISSUE TITLE
Pasted HTTP (requestJSON) script needs manual attention

### ISSUE THREAD

**Issue by rwu2359** [proofgeist/generator#7]
When I pasted the script to a new file, the ¶ characters which are in the stored XML get converted to
"
" 
- a literal carriage return, 
but then the script seem to not replace the CR in this line #74 -- Substitute( $responseHeader ; ":" ; ¶ ) (this is my edited version) and as a result Trim ( GetValue ( $responseHeader ; 2 ) ) then fails

Also line #60 has the calculation commented out which it needs otherwise line #65 fails.

**Comment by toddgeist** [comment]
I don't see this, can you attach a screen shot that shows the issue?

**Comment by toddgeist** [comment]
@rwu2359 will you check the latest version.  See if this has been resolved for you.

**Comment by rwu2359** [comment]
This is fixed in the latest version....

the issue I was getting is in screenshot...

<img width="661" alt="screen shot 2016-11-14 at 09 51 43" src="https://cloud.githubusercontent.com/assets/779522/20260113/1a9586d2-aa50-11e6-90cf-92cf6df9454a.png">

**Comment by toddgeist** [comment]
excellent
